<?php

namespace App;

use App\Scopes\SellerScope;
use Illuminate\Database\Eloquent\Model;

class Seller extends User
{
    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope(new SellerScope());
        // TODO: Change the autogenerated stub
    }

    //
    public function products(){
        return $this->hasMany(Product::class);
    }
}
